"use client";

import Link from "next/link";
import { deletePerson, savePerson } from "@/actions/people";
import { CloudinaryAssetField } from "@/components/content/cloudinary-asset-field";
import { ActionForm } from "@/components/feedback/action-form";
import type { PersonRow } from "@/components/content/people-editor";

const input = "mt-1.5 w-full border border-white/15 bg-[#09090b] px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/25 focus:border-emerald-300";

export function PersonForm({ person }: { person?: PersonRow }) {
  const image = person?.imageUrl ? [{ id: person.imageAssetId ?? undefined, url: person.imageUrl }] : [];
  return <div className="mt-8 max-w-4xl"><ActionForm action={savePerson} pendingMessage={person ? "Saving officer…" : "Creating officer…"} successMessage={person ? "Officer saved." : "Officer created."} className="space-y-6 border border-white/10 bg-[#111113] p-5 md:p-7">
    {person && <input type="hidden" name="id" value={person.id} />}<input type="hidden" name="displayOrder" value={person?.displayOrder ?? 0} />
    <div className="flex flex-col gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold text-white">{person ? `Edit ${person.name}` : "Add one officer"}</h1><p className="mt-2 text-sm leading-6 text-white/55">Update the profile, portrait, placement, and public publishing status in one place.</p></div><Link href="/content/people" className="w-fit border border-white/15 px-3 py-2 text-xs font-medium text-white/70 hover:border-white/35 hover:text-white">BACK TO ROSTER</Link></div>
    <div className="grid gap-5 md:grid-cols-2"><label className="text-xs font-medium tracking-[0.12em] text-white/65">FULL NAME<input required name="name" defaultValue={person?.name} className={input} /></label><label className="text-xs font-medium tracking-[0.12em] text-white/65">ROLE<input required name="role" defaultValue={person?.role} placeholder="President" className={input} /></label><label className="text-xs font-medium tracking-[0.12em] text-white/65">ORGANIZATION<select name="organization" defaultValue={person?.organization ?? "comsoc"} className={input}><option value="comsoc">COMSOC</option><option value="ccs_elites">CCS Elites</option></select></label><label className="text-xs font-medium tracking-[0.12em] text-white/65">TYPE<select name="personKind" defaultValue={person?.personKind ?? "officer"} className={input}><option value="officer">Officer</option><option value="adviser">Adviser</option></select></label><label className="text-xs font-medium tracking-[0.12em] text-white/65">ROW<select name="tier" defaultValue={person?.tier ?? 0} className={input}><option value="0">Row 1</option><option value="1">Row 2</option><option value="2">Row 3</option></select></label><label className="text-xs font-medium tracking-[0.12em] text-white/65">PUBLISH STATUS<select name="status" defaultValue={person?.status ?? "draft"} className={input}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="text-xs font-medium tracking-[0.12em] text-white/65">DEPARTMENT<input name="department" defaultValue={person?.department ?? ""} className={input} /></label><label className="text-xs font-medium tracking-[0.12em] text-white/65">EMAIL<input name="email" type="email" defaultValue={person?.email ?? ""} className={input} /></label><label className="text-xs font-medium tracking-[0.12em] text-white/65 md:col-span-2">FACEBOOK URL <span className="font-normal normal-case tracking-normal text-white/40">(optional)</span><input name="facebookUrl" type="url" defaultValue={person?.facebookUrl ?? ""} className={input} /></label><div className="md:col-span-2"><CloudinaryAssetField name="imageUrl" initialAssets={image} label="PORTRAIT" /></div></div>
    <div className="flex justify-end border-t border-white/10 pt-5"><button className="bg-emerald-300 px-4 py-2.5 text-xs font-semibold tracking-[0.12em] text-[#07110d] hover:bg-emerald-200">{person ? "SAVE CHANGES" : "CREATE OFFICER"}</button></div>
  </ActionForm>{person && <form action={deletePerson} className="mt-4 text-right"><input type="hidden" name="id" value={person.id} /><button className="text-xs text-red-300 underline underline-offset-4">DELETE PERSON PERMANENTLY</button></form>}</div>;
}
